-- ######################################################################
-- # Oracle 19c 电信业务基础实验数据库脚本 (V7 - 生产实践无Prompt优化)#
-- # 作者: AI Assistant                                               #
-- # 日期: 2023-10-27                                                 #
-- # 目的: 创建一套模拟电信BOSS/CRM/BILLING/能力开放业务的表结构和测试数据 #
-- #       全面优化为RAC+ASM部署，表空间统一放在DGDATA01下             #
-- #       所有表、索引、序列所在表空间均为BIGFILE TABLESPACE            #
-- #       业务用户命名<=4字母，并创建年表、月表、日表学习示例           #
-- #       移除所有PROMPT语句，确保脚本安静执行                         #
-- ######################################################################

-- ======================================================================
-- 1. 设置会话环境
-- ======================================================================
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF';

-- ======================================================================
-- 2. 清理现有对象 (如果需要重新运行此脚本)
--    顺序很重要：先删除用户，再删除表空间。请谨慎操作！
-- ======================================================================

-- 删除职能用户
BEGIN EXECUTE IMMEDIATE 'DROP USER TELECOM_DBA CASCADE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -01918 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER TELECOM_DEV CASCADE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -01918 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER TELECOM_OPS CASCADE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -01918 THEN NULL; ELSE RAISE; END IF; END;
/

-- 删除业务Schema用户
BEGIN EXECUTE IMMEDIATE 'DROP USER TCBS CASCADE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -01918 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER TCOA CASCADE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -01918 THEN NULL; ELSE RAISE; END IF; END;
/

-- 删除所有相关表空间
-- 主业务表空间
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TS_TCBS_DATA INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TS_TCBS_IDX INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TS_TCBS_LOB INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TS_TCOA_DATA INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TS_TCOA_IDX INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/

-- 年表空间 (TCBS, 示例2023年)
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCBS_YR_DAT_2023 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCBS_YR_IND_2023 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/

-- 月表空间 (TCBS, 示例2023年10月-12月, 清理周期03)
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCBS_MON_03_DAT_202310 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCBS_MON_03_IND_202310 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCBS_MON_03_DAT_202311 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCBS_MON_03_IND_202311 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCBS_MON_03_DAT_202312 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCBS_MON_03_IND_202312 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/

-- 月表空间 (TCOA, 示例2023年10月-12月, 清理周期03)
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCOA_MON_03_DAT_202310 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCOA_MON_03_IND_202310 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCOA_MON_03_DAT_202311 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCOA_MON_03_IND_202311 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCOA_MON_03_DAT_202312 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_TCOA_MON_03_IND_202312 INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -00959 THEN NULL; ELSE RAISE; END IF; END;
/


-- ======================================================================
-- 3. 创建表空间 (Tablespaces) - 统一放置在 ASM Diskgroup +DGDATA01
--    所有表空间均为 BIGFILE TABLESPACE，数据文件由 OMF 自动创建和命名。
-- ======================================================================

-- 业务数据表空间 (TCBS)
CREATE BIGFILE TABLESPACE TS_TCBS_DATA DATAFILE '+DGDATA01' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;
-- 业务索引表空间 (TCBS)
CREATE BIGFILE TABLESPACE TS_TCBS_IDX DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;
-- LOB数据表空间 (TCBS & TCOA 共享，也可根据需求创建独立的)
CREATE BIGFILE TABLESPACE TS_TCBS_LOB DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;

-- 能力开放APP数据表空间 (TCOA)
CREATE BIGFILE TABLESPACE TS_TCOA_DATA DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;
-- 能力开放APP索引表空间 (TCOA)
CREATE BIGFILE TABLESPACE TS_TCOA_IDX DATAFILE '+DGDATA01' SIZE 25M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;


-- ######################################################################
-- # 历史数据表空间 - 年表 (手动清理，无清理周期标识)                   #
-- ######################################################################

-- TCBS 2023年数据年表空间
CREATE BIGFILE TABLESPACE TBS_TCBS_YR_DAT_2023 DATAFILE '+DGDATA01' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;
-- TCBS 2023年索引年表空间
CREATE BIGFILE TABLESPACE TBS_TCBS_YR_IND_2023 DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;


-- ######################################################################
-- # 历史数据表空间 - 月表 (清理周期03个月)                            #
-- ######################################################################

-- TCBS 2023年10月数据月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCBS_MON_03_DAT_202310 DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;
-- TCBS 2023年10月索引月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCBS_MON_03_IND_202310 DATAFILE '+DGDATA01' SIZE 25M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- TCBS 2023年11月数据月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCBS_MON_03_DAT_202311 DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;
-- TCBS 2023年11月索引月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCBS_MON_03_IND_202311 DATAFILE '+DGDATA01' SIZE 25M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- TCBS 2023年12月数据月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCBS_MON_03_DAT_202312 DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;
-- TCBS 2023年12月索引月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCBS_MON_03_IND_202312 DATAFILE '+DGDATA01' SIZE 25M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- TCOA 2023年10月数据月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCOA_MON_03_DAT_202310 DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;
-- TCOA 2023年10月索引月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCOA_MON_03_IND_202310 DATAFILE '+DGDATA01' SIZE 25M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- TCOA 2023年11月数据月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCOA_MON_03_DAT_202311 DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;
-- TCOA 2023年11月索引月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCOA_MON_03_IND_202311 DATAFILE '+DGDATA01' SIZE 25M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- TCOA 2023年12月数据月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCOA_MON_03_DAT_202312 DATAFILE '+DGDATA01' SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;
-- TCOA 2023年12月索引月表空间 (清理周期03)
CREATE BIGFILE TABLESPACE TBS_TCOA_MON_03_IND_202312 DATAFILE '+DGDATA01' SIZE 25M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;


-- ======================================================================
-- 4. 创建业务Schema用户 (Owners of Business Objects)
--    使用新的短名称 <=4 字母
-- ======================================================================

-- 1. TCBS 用户 (Telecom Business System - 拥有CRM, BILLING, Products, Contracts等对象)
CREATE USER TCBS IDENTIFIED BY "Tcbs_123"
DEFAULT TABLESPACE TS_TCBS_DATA
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

-- 授予TCBS创建会话和对象的能力，并设置表空间配额
GRANT CONNECT, RESOURCE TO TCBS;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO TCBS;
ALTER USER TCBS QUOTA UNLIMITED ON TS_TCBS_DATA;
ALTER USER TCBS QUOTA UNLIMITED ON TS_TCBS_IDX;
ALTER USER TCBS QUOTA UNLIMITED ON TS_TCBS_LOB;
-- 授予对历史表空间的配额，如果未来需要直接在这些表空间中创建对象
ALTER USER TCBS QUOTA UNLIMITED ON TBS_TCBS_YR_DAT_2023;
ALTER USER TCBS QUOTA UNLIMITED ON TBS_TCBS_YR_IND_2023;
ALTER USER TCBS QUOTA UNLIMITED ON TBS_TCBS_MON_03_DAT_202310;
ALTER USER TCBS QUOTA UNLIMITED ON TBS_TCBS_MON_03_IND_202310;
ALTER USER TCBS QUOTA UNLIMITED ON TBS_TCBS_MON_03_DAT_202311;
ALTER USER TCBS QUOTA UNLIMITED ON TBS_TCBS_MON_03_IND_202311;
ALTER USER TCBS QUOTA UNLIMITED ON TBS_TCBS_MON_03_DAT_202312;
ALTER USER TCBS QUOTA UNLIMITED ON TBS_TCBS_MON_03_IND_202312;

-- 2. TCOA 用户 (Telecom Open API System - 拥有API Apps, API Logs等对象)
CREATE USER TCOA IDENTIFIED BY "Tcoa_123"
DEFAULT TABLESPACE TS_TCOA_DATA
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

-- 授予TCOA创建会话和对象的能力，并设置表空间配额
GRANT CONNECT, RESOURCE TO TCOA;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO TCOA;
ALTER USER TCOA QUOTA UNLIMITED ON TS_TCOA_DATA;
ALTER USER TCOA QUOTA UNLIMITED ON TS_TCOA_IDX;
ALTER USER TCOA QUOTA UNLIMITED ON TS_TCBS_LOB; -- TCOA可能也使用TCBS的LOB表空间
-- 授予对历史表空间的配额
ALTER USER TCOA QUOTA UNLIMITED ON TBS_TCOA_MON_03_DAT_202310;
ALTER USER TCOA QUOTA UNLIMITED ON TBS_TCOA_MON_03_IND_202310;
ALTER USER TCOA QUOTA UNLIMITED ON TBS_TCOA_MON_03_DAT_202311;
ALTER USER TCOA QUOTA UNLIMITED ON TBS_TCOA_MON_03_IND_202311;
ALTER USER TCOA QUOTA UNLIMITED ON TBS_TCOA_MON_03_DAT_202312;
ALTER USER TCOA QUOTA UNLIMITED ON TBS_TCOA_MON_03_IND_202312;

-- ======================================================================
-- 5. 创建序列 (Sequences) - 以TCBS和TCOA的身份创建
--    序列将创建在对应用户的默认表空间中 (TS_TCBS_DATA, TS_TCOA_DATA), 它们现在都是大表空间。
-- ======================================================================

-- TCBS Schema的序列
CREATE SEQUENCE TCBS.CUSTOMER_SEQ START WITH 100001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCBS.ACCOUNT_SEQ START WITH 200001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCBS.CONTRACT_SEQ START WITH 300001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCBS.PRODUCT_CAT_SEQ START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCBS.TELECOM_PROD_SEQ START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCBS.CUST_PROD_SEQ START WITH 400001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCBS.BILL_SEQ START WITH 500001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCBS.BILL_ITEM_SEQ START WITH 600001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCBS.USAGE_REC_SEQ START WITH 700001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCBS.NUMBER_RES_SEQ START WITH 13000000000 INCREMENT BY 1 NOCACHE MINVALUE 13000000000 MAXVALUE 19999999999;

-- TCOA Schema的序列
CREATE SEQUENCE TCOA.API_APP_SEQ START WITH 800001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TCOA.API_CALL_SEQ START WITH 900001 INCREMENT BY 1 NOCACHE;

-- ======================================================================
-- 6. 创建表结构 (Tables) - 分别在TCBS和TCOA的Schema下
--    同时指定表和索引的表空间，LOB段的表空间
-- ======================================================================

-- TCBS Schema 的表
-- 客户表 (CRM核心)
CREATE TABLE TCBS.CUSTOMERS (
    customer_id     NUMBER(10)      DEFAULT TCBS.CUSTOMER_SEQ.NEXTVAL NOT NULL,
    id_type         VARCHAR2(20)    DEFAULT 'ID_CARD' CHECK (id_type IN ('ID_CARD', 'PASSPORT', 'DRIVER_LICENSE')),
    id_number       VARCHAR2(50)    CONSTRAINT tcbs_cust_id_num_uk UNIQUE NOT NULL,
    customer_name   VARCHAR2(100)   CONSTRAINT tcbs_cust_name_nn NOT NULL,
    contact_phone   VARCHAR2(20)    CONSTRAINT tcbs_cust_phone_uk UNIQUE,
    contact_email   VARCHAR2(100),
    address_line1   VARCHAR2(100),
    city            VARCHAR2(50),
    province        VARCHAR2(50),
    postal_code     VARCHAR2(10),
    status          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CANCELLED')),
    registration_date TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    last_update_date  TIMESTAMP,
    CONSTRAINT      pk_tcbs_customers PRIMARY KEY (customer_id) USING INDEX TABLESPACE TS_TCBS_IDX
) TABLESPACE TS_TCBS_DATA
;

-- 客户账户表 (BOSS核心)
CREATE TABLE TCBS.CUSTOMER_ACCOUNTS (
    account_id      NUMBER(10)      DEFAULT TCBS.ACCOUNT_SEQ.NEXTVAL NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_acct_cust_id_nn NOT NULL,
    account_name    VARCHAR2(100)   CONSTRAINT tcbs_acct_name_nn NOT NULL,
    account_type    VARCHAR2(20)    DEFAULT 'INDIVIDUAL' CHECK (account_type IN ('INDIVIDUAL', 'FAMILY', 'BUSINESS')),
    balance         NUMBER(12,2)    DEFAULT 0.00,
    credit_limit    NUMBER(12,2)    DEFAULT 0.00,
    status          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'PENDING', 'CLOSED')),
    open_date       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    close_date      TIMESTAMP,
    CONSTRAINT      pk_tcbs_customer_accounts PRIMARY KEY (account_id) USING INDEX TABLESPACE TS_TCBS_IDX,
    CONSTRAINT      fk_tcbs_acct_cust FOREIGN KEY (customer_id) REFERENCES TCBS.CUSTOMERS (customer_id),
    CONSTRAINT      uk_tcbs_cust_acct_name UNIQUE (customer_id, account_name) USING INDEX TABLESPACE TS_TCBS_IDX
) TABLESPACE TS_TCBS_DATA
;

-- 产品类别表 (BOSS/产品管理)
CREATE TABLE TCBS.PRODUCT_CATEGORIES (
    category_id     NUMBER(5)       DEFAULT TCBS.PRODUCT_CAT_SEQ.NEXTVAL NOT NULL,
    category_name   VARCHAR2(100)   CONSTRAINT tcbs_prod_cat_name_nn NOT NULL,
    description     VARCHAR2(500),
    CONSTRAINT      pk_tcbs_product_categories PRIMARY KEY (category_id) USING INDEX TABLESPACE TS_TCBS_IDX,
    CONSTRAINT      uk_tcbs_prod_cat_name UNIQUE (category_name) USING INDEX TABLESPACE TS_TCBS_IDX
) TABLESPACE TS_TCBS_DATA
;

-- 电信产品/服务表 (BOSS/产品管理)
CREATE TABLE TCBS.TELECOM_PRODUCTS (
    product_id      NUMBER(10)      DEFAULT TCBS.TELECOM_PROD_SEQ.NEXTVAL NOT NULL,
    product_name    VARCHAR2(100)   CONSTRAINT tcbs_tp_name_nn NOT NULL,
    category_id     NUMBER(5)       CONSTRAINT tcbs_tp_cat_id_nn NOT NULL,
    product_type    VARCHAR2(20)    DEFAULT 'PACKAGE' CHECK (product_type IN ('PACKAGE', 'VOICE_PLAN', 'DATA_PLAN', 'VAS', 'DEVICE')),
    base_price      NUMBER(10,2)    DEFAULT 0.00 CHECK (base_price >= 0),
    description     CLOB,
    validity_period_days NUMBER(5),
    is_active       CHAR(1)         DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    created_date    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT      pk_tcbs_telecom_products PRIMARY KEY (product_id) USING INDEX TABLESPACE TS_TCBS_IDX,
    CONSTRAINT      fk_tcbs_tp_cat FOREIGN KEY (category_id) REFERENCES TCBS.PRODUCT_CATEGORIES (category_id),
    CONSTRAINT      uk_tcbs_tp_name UNIQUE (product_name) USING INDEX TABLESPACE TS_TCBS_IDX
) TABLESPACE TS_TCBS_DATA
LOB (description) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
;

-- 号码资源表 (BOSS/资源管理)
CREATE TABLE TCBS.NUMBER_RESOURCES (
    resource_id     NUMBER(15)      DEFAULT TCBS.NUMBER_RES_SEQ.NEXTVAL NOT NULL, -- 模拟手机号码
    resource_type   VARCHAR2(20)    DEFAULT 'MOBILE_NUMBER' CHECK (resource_type IN ('MOBILE_NUMBER', 'BROADBAND_ACCOUNT', 'IP_ADDRESS')),
    status          VARCHAR2(20)    DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'ASSIGNED', 'RESERVED', 'DEACTIVATED')),
    assigned_to_customer_id NUMBER(10),
    assigned_date   TIMESTAMP,
    CONSTRAINT      pk_tcbs_number_resources PRIMARY KEY (resource_id) USING INDEX TABLESPACE TS_TCBS_IDX
) TABLESPACE TS_TCBS_DATA
;

-- 服务合同表 (BOSS/CRM)
CREATE TABLE TCBS.SERVICE_CONTRACTS (
    contract_id     NUMBER(10)      DEFAULT TCBS.CONTRACT_SEQ.NEXTVAL NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_sc_cust_id_nn NOT NULL,
    account_id      NUMBER(10)      CONSTRAINT tcbs_sc_acct_id_nn NOT NULL,
    resource_id     NUMBER(15),
    start_date      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    end_date        TIMESTAMP,
    contract_status VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (contract_status IN ('ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED')),
    monthly_fee     NUMBER(10,2)    DEFAULT 0.00,
    CONSTRAINT      pk_tcbs_service_contracts PRIMARY KEY (contract_id) USING INDEX TABLESPACE TS_TCBS_IDX,
    CONSTRAINT      fk_tcbs_sc_cust FOREIGN KEY (customer_id) REFERENCES TCBS.CUSTOMERS (customer_id),
    CONSTRAINT      fk_tcbs_sc_acct FOREIGN KEY (account_id) REFERENCES TCBS.CUSTOMER_ACCOUNTS (account_id),
    CONSTRAINT      fk_tcbs_sc_res FOREIGN KEY (resource_id) REFERENCES TCBS.NUMBER_RESOURCES (resource_id)
) TABLESPACE TS_TCBS_DATA
;

-- 客户已订购产品表 (CRM/BOSS - 客户和产品实际关联)
CREATE TABLE TCBS.CUSTOMER_PRODUCTS (
    cust_product_id NUMBER(10)      DEFAULT TCBS.CUST_PROD_SEQ.NEXTVAL NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_cp_cust_id_nn NOT NULL,
    account_id      NUMBER(10)      CONSTRAINT tcbs_cp_acct_id_nn NOT NULL,
    product_id      NUMBER(10)      CONSTRAINT tcbs_cp_prod_id_nn NOT NULL,
    contract_id     NUMBER(10),
    subscribe_date  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    expire_date     TIMESTAMP,
    status          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT      pk_tcbs_customer_products PRIMARY KEY (cust_product_id) USING INDEX TABLESPACE TS_TCBS_IDX,
    CONSTRAINT      fk_tcbs_cp_cust FOREIGN KEY (customer_id) REFERENCES TCBS.CUSTOMERS (customer_id),
    CONSTRAINT      fk_tcbs_cp_acct FOREIGN KEY (account_id) REFERENCES TCBS.CUSTOMER_ACCOUNTS (account_id),
    CONSTRAINT      fk_tcbs_cp_prod FOREIGN KEY (product_id) REFERENCES TCBS.TELECOM_PRODUCTS (product_id),
    CONSTRAINT      fk_tcbs_cp_contract FOREIGN KEY (contract_id) REFERENCES TCBS.SERVICE_CONTRACTS (contract_id)
) TABLESPACE TS_TCBS_DATA
;

-- 客户账单表 (BILLING核心)
CREATE TABLE TCBS.CUSTOMER_BILLS (
    bill_id         NUMBER(10)      DEFAULT TCBS.BILL_SEQ.NEXTVAL NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_cb_cust_id_nn NOT NULL,
    account_id      NUMBER(10)      CONSTRAINT tcbs_cb_acct_id_nn NOT NULL,
    bill_period_start TIMESTAMP     CONSTRAINT tcbs_cb_period_start_nn NOT NULL,
    bill_period_end   TIMESTAMP     CONSTRAINT tcbs_cb_period_end_nn NOT NULL,
    total_amount    NUMBER(12,2)    CONSTRAINT tcbs_cb_total_amt_nn NOT NULL CHECK (total_amount >= 0),
    paid_amount     NUMBER(12,2)    DEFAULT 0.00 CHECK (paid_amount >= 0),
    due_date        DATE            CONSTRAINT tcbs_cb_due_date_nn NOT NULL,
    payment_status  VARCHAR2(20)    DEFAULT 'UNPAID' CHECK (payment_status IN ('UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE')),
    generated_date  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT      pk_tcbs_customer_bills PRIMARY KEY (bill_id) USING INDEX TABLESPACE TS_TCBS_IDX,
    CONSTRAINT      fk_tcbs_cb_cust FOREIGN KEY (customer_id) REFERENCES TCBS.CUSTOMERS (customer_id),
    CONSTRAINT      fk_tcbs_cb_acct FOREIGN KEY (account_id) REFERENCES TCBS.CUSTOMER_ACCOUNTS (account_id),
    CONSTRAINT      uk_tcbs_cust_acct_period UNIQUE (account_id, bill_period_start, bill_period_end) USING INDEX TABLESPACE TS_TCBS_IDX
) TABLESPACE TS_TCBS_DATA
;

-- 账单明细项 (BILLING明细)
CREATE TABLE TCBS.BILL_ITEMS (
    bill_item_id    NUMBER(10)      DEFAULT TCBS.BILL_ITEM_SEQ.NEXTVAL NOT NULL,
    bill_id         NUMBER(10)      CONSTRAINT tcbs_bi_bill_id_nn NOT NULL,
    item_description VARCHAR2(200)   CONSTRAINT tcbs_bi_desc_nn NOT NULL,
    item_type       VARCHAR2(50)    CHECK (item_type IN ('MONTHLY_FEE', 'VOICE_USAGE', 'DATA_USAGE', 'SMS_USAGE', 'VAS_FEE', 'ADJUSTMENT')),
    amount          NUMBER(10,2)    CONSTRAINT tcbs_bi_amt_nn NOT NULL,
    CONSTRAINT      pk_tcbs_bill_items PRIMARY KEY (bill_item_id) USING INDEX TABLESPACE TS_TCBS_IDX,
    CONSTRAINT      fk_tcbs_bi_bill FOREIGN KEY (bill_id) REFERENCES TCBS.CUSTOMER_BILLS (bill_id)
) TABLESPACE TS_TCBS_DATA
;

-- 使用记录 (BILLING/BOSS - 原始使用数据，如通话、流量 - 将会有年表和月表)
CREATE TABLE TCBS.USAGE_RECORDS (
    usage_id        NUMBER(15)      DEFAULT TCBS.USAGE_REC_SEQ.NEXTVAL NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_ur_cust_id_nn NOT NULL,
    account_id      NUMBER(10)      CONSTRAINT tcbs_ur_acct_id_nn NOT NULL,
    resource_id     NUMBER(15),
    usage_type      VARCHAR2(20)    CHECK (usage_type IN ('VOICE', 'DATA', 'SMS')),
    usage_start_time TIMESTAMP      CONSTRAINT tcbs_ur_start_time_nn NOT NULL,
    usage_end_time  TIMESTAMP,
    duration_seconds NUMBER(10),
    data_volume_mb   NUMBER(12,3),
    sms_count        NUMBER(5),
    cost            NUMBER(10,4),
    called_number   VARCHAR2(20),
    data_service_type VARCHAR2(50),
    CONSTRAINT      pk_tcbs_usage_records PRIMARY KEY (usage_id) USING INDEX TABLESPACE TS_TCBS_IDX,
    CONSTRAINT      fk_tcbs_ur_cust FOREIGN KEY (customer_id) REFERENCES TCBS.CUSTOMERS (customer_id),
    CONSTRAINT      fk_tcbs_ur_acct FOREIGN KEY (account_id) REFERENCES TCBS.CUSTOMER_ACCOUNTS (account_id),
    CONSTRAINT      fk_tcbs_ur_res FOREIGN KEY (resource_id) REFERENCES TCBS.NUMBER_RESOURCES (resource_id)
) TABLESPACE TS_TCBS_DATA
;


-- TCOA Schema 的表
-- 能力开放：第三方应用表 (能力开放)
CREATE TABLE TCOA.OPEN_API_APPS (
    app_id          NUMBER(10)      DEFAULT TCOA.API_APP_SEQ.NEXTVAL NOT NULL,
    app_name        VARCHAR2(100)   CONSTRAINT tcoa_app_name_nn NOT NULL,
    developer_name  VARCHAR2(100),
    app_key         VARCHAR2(64)    CONSTRAINT tcoa_app_key_uk UNIQUE NOT NULL,
    app_secret      VARCHAR2(128)   CONSTRAINT tcoa_app_secret_nn NOT NULL,
    status          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED')),
    registered_date TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT      pk_tcoa_api_apps PRIMARY KEY (app_id) USING INDEX TABLESPACE TS_TCOA_IDX
) TABLESPACE TS_TCOA_DATA
;

-- 能力开放：API调用日志表 (能力开放 - 巨量数据 - 将会有月表)
CREATE TABLE TCOA.API_CALL_LOGS (
    log_id          NUMBER(15)      DEFAULT TCOA.API_CALL_SEQ.NEXTVAL NOT NULL,
    app_id          NUMBER(10)      CONSTRAINT tcoa_acl_app_id_nn NOT NULL,
    api_endpoint    VARCHAR2(200)   CONSTRAINT tcoa_acl_endpoint_nn NOT NULL,
    call_timestamp  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    request_method  VARCHAR2(10)    CHECK (request_method IN ('GET', 'POST', 'PUT', 'DELETE')),
    response_status NUMBER(3)       CONSTRAINT tcoa_acl_resp_status_nn NOT NULL,
    response_time_ms NUMBER(10),
    request_body    CLOB,
    response_body   CLOB,
    client_ip       VARCHAR2(40),
    customer_id     NUMBER(10),
    CONSTRAINT      pk_tcoa_api_call_logs PRIMARY KEY (log_id) USING INDEX TABLESPACE TS_TCOA_IDX,
    CONSTRAINT      fk_tcoa_acl_app FOREIGN KEY (app_id) REFERENCES TCOA.OPEN_API_APPS (app_id)
) TABLESPACE TS_TCOA_DATA
LOB (request_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB) -- 共享LOB表空间
LOB (response_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
;


-- ######################################################################
-- # 创建年表、月表、日表示例 (用于历史数据归档学习)                   #
-- ######################################################################

-- 1. TCBS.USAGE_RECORDS 的年表示例 (2023年)
CREATE TABLE TCBS.USAGE_RECORDS_YR_2023 (
    usage_id        NUMBER(15)      NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_ury_cust_id_nn_23 NOT NULL,
    account_id      NUMBER(10)      CONSTRAINT tcbs_ury_acct_id_nn_23 NOT NULL,
    resource_id     NUMBER(15),
    usage_type      VARCHAR2(20),
    usage_start_time TIMESTAMP      CONSTRAINT tcbs_ury_start_time_nn_23 NOT NULL,
    usage_end_time  TIMESTAMP,
    duration_seconds NUMBER(10),
    data_volume_mb   NUMBER(12,3),
    sms_count        NUMBER(5),
    cost            NUMBER(10,4),
    called_number   VARCHAR2(20),
    data_service_type VARCHAR2(50),
    CONSTRAINT      pk_tcbs_ury_2023 PRIMARY KEY (usage_id) USING INDEX TABLESPACE TBS_TCBS_YR_IND_2023
) TABLESPACE TBS_TCBS_YR_DAT_2023
;

-- 2. TCBS.USAGE_RECORDS 的月表示例 (2023年10月-12月)
-- 2023年10月
CREATE TABLE TCBS.USAGE_RECORDS_MON_202310 (
    usage_id        NUMBER(15)      NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_urm_cust_id_nn_2310 NOT NULL,
    account_id      NUMBER(10)      CONSTRAINT tcbs_urm_acct_id_nn_2310 NOT NULL,
    resource_id     NUMBER(15),
    usage_type      VARCHAR2(20),
    usage_start_time TIMESTAMP      CONSTRAINT tcbs_urm_start_time_nn_2310 NOT NULL,
    usage_end_time  TIMESTAMP,
    duration_seconds NUMBER(10),
    data_volume_mb   NUMBER(12,3),
    sms_count        NUMBER(5),
    cost            NUMBER(10,4),
    called_number   VARCHAR2(20),
    data_service_type VARCHAR2(50),
    CONSTRAINT      pk_tcbs_urm_202310 PRIMARY KEY (usage_id) USING INDEX TABLESPACE TBS_TCBS_MON_03_IND_202310
) TABLESPACE TBS_TCBS_MON_03_DAT_202310
;
-- 2023年11月
CREATE TABLE TCBS.USAGE_RECORDS_MON_202311 (
    usage_id        NUMBER(15)      NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_urm_cust_id_nn_2311 NOT NULL,
    account_id      NUMBER(10)      CONSTRAINT tcbs_urm_acct_id_nn_2311 NOT NULL,
    resource_id     NUMBER(15),
    usage_type      VARCHAR2(20),
    usage_start_time TIMESTAMP      CONSTRAINT tcbs_urm_start_time_nn_2311 NOT NULL,
    usage_end_time  TIMESTAMP,
    duration_seconds NUMBER(10),
    data_volume_mb   NUMBER(12,3),
    sms_count        NUMBER(5),
    cost            NUMBER(10,4),
    called_number   VARCHAR2(20),
    data_service_type VARCHAR2(50),
    CONSTRAINT      pk_tcbs_urm_202311 PRIMARY KEY (usage_id) USING INDEX TABLESPACE TBS_TCBS_MON_03_IND_202311
) TABLESPACE TBS_TCBS_MON_03_DAT_202311
;
-- 2023年12月
CREATE TABLE TCBS.USAGE_RECORDS_MON_202312 (
    usage_id        NUMBER(15)      NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_urm_cust_id_nn_2312 NOT NULL,
    account_id      NUMBER(10)      CONSTRAINT tcbs_urm_acct_id_nn_2312 NOT NULL,
    resource_id     NUMBER(15),
    usage_type      VARCHAR2(20),
    usage_start_time TIMESTAMP      CONSTRAINT tcbs_urm_start_time_nn_2312 NOT NULL,
    usage_end_time  TIMESTAMP,
    duration_seconds NUMBER(10),
    data_volume_mb   NUMBER(12,3),
    sms_count        NUMBER(5),
    cost            NUMBER(10,4),
    called_number   VARCHAR2(20),
    data_service_type VARCHAR2(50),
    CONSTRAINT      pk_tcbs_urm_202312 PRIMARY KEY (usage_id) USING INDEX TABLESPACE TBS_TCBS_MON_03_IND_202312
) TABLESPACE TBS_TCBS_MON_03_DAT_202312
;

-- 3. TCBS.USAGE_RECORDS 的日表示例 (2023年10月26日) - 放在月表空间下
CREATE TABLE TCBS.USAGE_RECORDS_DAILY_20231026 (
    usage_id        NUMBER(15)      NOT NULL,
    customer_id     NUMBER(10)      CONSTRAINT tcbs_urd_cust_id_nn_231026 NOT NULL,
    account_id      NUMBER(10)      CONSTRAINT tcbs_urd_acct_id_nn_231026 NOT NULL,
    resource_id     NUMBER(15),
    usage_type      VARCHAR2(20),
    usage_start_time TIMESTAMP      CONSTRAINT tcbs_urd_start_time_nn_231026 NOT NULL,
    usage_end_time  TIMESTAMP,
    duration_seconds NUMBER(10),
    data_volume_mb   NUMBER(12,3),
    sms_count        NUMBER(5),
    cost            NUMBER(10,4),
    called_number   VARCHAR2(20),
    data_service_type VARCHAR2(50),
    CONSTRAINT      pk_tcbs_urd_20231026 PRIMARY KEY (usage_id) USING INDEX TABLESPACE TBS_TCBS_MON_03_IND_202310
) TABLESPACE TBS_TCBS_MON_03_DAT_202310
;

-- 4. TCOA.API_CALL_LOGS 的月表示例 (2023年10月-12月)
-- 2023年10月
CREATE TABLE TCOA.API_CALL_LOGS_MON_202310 (
    log_id          NUMBER(15)      NOT NULL,
    app_id          NUMBER(10)      CONSTRAINT tcoa_aclm_app_id_nn_2310 NOT NULL,
    api_endpoint    VARCHAR2(200)   CONSTRAINT tcoa_aclm_endpoint_nn_2310 NOT NULL,
    call_timestamp  TIMESTAMP       CONSTRAINT tcoa_aclm_ts_nn_2310 NOT NULL,
    request_method  VARCHAR2(10),
    response_status NUMBER(3)       CONSTRAINT tcoa_aclm_resp_status_nn_2310 NOT NULL,
    response_time_ms NUMBER(10),
    request_body    CLOB,
    response_body   CLOB,
    client_ip       VARCHAR2(40),
    customer_id     NUMBER(10),
    CONSTRAINT      pk_tcoa_aclm_202310 PRIMARY KEY (log_id) USING INDEX TABLESPACE TBS_TCOA_MON_03_IND_202310
) TABLESPACE TBS_TCOA_MON_03_DAT_202310
LOB (request_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
LOB (response_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
;
-- 2023年11月
CREATE TABLE TCOA.API_CALL_LOGS_MON_202311 (
    log_id          NUMBER(15)      NOT NULL,
    app_id          NUMBER(10)      CONSTRAINT tcoa_aclm_app_id_nn_2311 NOT NULL,
    api_endpoint    VARCHAR2(200)   CONSTRAINT tcoa_aclm_endpoint_nn_2311 NOT NULL,
    call_timestamp  TIMESTAMP       CONSTRAINT tcoa_aclm_ts_nn_2311 NOT NULL,
    request_method  VARCHAR2(10),
    response_status NUMBER(3)       CONSTRAINT tcoa_aclm_resp_status_nn_2311 NOT NULL,
    response_time_ms NUMBER(10),
    request_body    CLOB,
    response_body   CLOB,
    client_ip       VARCHAR2(40),
    customer_id     NUMBER(10),
    CONSTRAINT      pk_tcoa_aclm_202311 PRIMARY KEY (log_id) USING INDEX TABLESPACE TBS_TCOA_MON_03_IND_202311
) TABLESPACE TBS_TCOA_MON_03_DAT_202311
LOB (request_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
LOB (response_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
;
-- 2023年12月
CREATE TABLE TCOA.API_CALL_LOGS_MON_202312 (
    log_id          NUMBER(15)      NOT NULL,
    app_id          NUMBER(10)      CONSTRAINT tcoa_aclm_app_id_nn_2312 NOT NULL,
    api_endpoint    VARCHAR2(200)   CONSTRAINT tcoa_aclm_endpoint_nn_2312 NOT NULL,
    call_timestamp  TIMESTAMP       CONSTRAINT tcoa_aclm_ts_nn_2312 NOT NULL,
    request_method  VARCHAR2(10),
    response_status NUMBER(3)       CONSTRAINT tcoa_aclm_resp_status_nn_2312 NOT NULL,
    response_time_ms NUMBER(10),
    request_body    CLOB,
    response_body   CLOB,
    client_ip       VARCHAR2(40),
    customer_id     NUMBER(10),
    CONSTRAINT      pk_tcoa_aclm_202312 PRIMARY KEY (log_id) USING INDEX TABLESPACE TBS_TCOA_MON_03_IND_202312
) TABLESPACE TBS_TCOA_MON_03_DAT_202312
LOB (request_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
LOB (response_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
;

-- ======================================================================
-- 7. 授予业务Schema用户之间的引用权限 (如果存在跨Schema引用)
-- ======================================================================

-- TCOA的API_CALL_LOGS表需要引用TCBS的CUSTOMERS表
GRANT SELECT ON TCBS.CUSTOMERS TO TCOA;

-- 添加外键约束
-- ALTER TABLE TCOA.API_CALL_LOGS ADD CONSTRAINT fk_tcoa_acl_cust FOREIGN KEY (customer_id) REFERENCES TCBS.CUSTOMERS (customer_id);

-- ======================================================================
-- 8. 创建职能用户 (DBA, DEVELOPER, OPERATOR)
--    他们通过角色和权限访问业务Schema中的对象
-- ======================================================================

-- 1. TELECOM_DBA 用户
CREATE USER TELECOM_DBA IDENTIFIED BY "TelecomDba_123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE, DBA TO TELECOM_DBA; -- DBA角色具有最高权限
GRANT SELECT ANY DICTIONARY TO TELECOM_DBA;
GRANT UNLIMITED TABLESPACE TO TELECOM_DBA;

GRANT SELECT_CATALOG_ROLE TO TELECOM_DBA;
COMMIT;

-- 2. TELECOM_DEV 用户
CREATE USER TELECOM_DEV IDENTIFIED BY "TelecomDev_123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

-- 开发人员通常需要对业务Schema有SELECT, INSERT, UPDATE, DELETE权限
-- 并且可能需要CREATE VIEW, CREATE PROCEDURE等在自己的Schema下创建开发辅助对象
GRANT CONNECT TO TELECOM_DEV;
GRANT CREATE SESSION TO TELECOM_DEV;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SYNONYM TO TELECOM_DEV;
-- 授予对TCBS和TCOA Schema的常用DML权限
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.CUSTOMERS TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.CUSTOMER_ACCOUNTS TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.PRODUCT_CATEGORIES TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.TELECOM_PRODUCTS TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.NUMBER_RESOURCES TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.SERVICE_CONTRACTS TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.CUSTOMER_PRODUCTS TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.CUSTOMER_BILLS TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.BILL_ITEMS TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCBS.USAGE_RECORDS TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCOA.OPEN_API_APPS TO TELECOM_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON TCOA.API_CALL_LOGS TO TELECOM_DEV;
-- 授予对历史表的SELECT权限 (DML通常由ETL程序用户执行)
GRANT SELECT ON TCBS.USAGE_RECORDS_YR_2023 TO TELECOM_DEV;
GRANT SELECT ON TCBS.USAGE_RECORDS_MON_202310 TO TELECOM_DEV;
GRANT SELECT ON TCBS.USAGE_RECORDS_MON_202311 TO TELECOM_DEV;
GRANT SELECT ON TCBS.USAGE_RECORDS_MON_202312 TO TELECOM_DEV;
GRANT SELECT ON TCBS.USAGE_RECORDS_DAILY_20231026 TO TELECOM_DEV;
GRANT SELECT ON TCOA.API_CALL_LOGS_MON_202310 TO TELECOM_DEV;
GRANT SELECT ON TCOA.API_CALL_LOGS_MON_202311 TO TELECOM_DEV;
GRANT SELECT ON TCOA.API_CALL_LOGS_MON_202312 TO TELECOM_DEV;

-- 授予序列的使用权限
GRANT SELECT ON TCBS.CUSTOMER_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCBS.ACCOUNT_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCBS.CONTRACT_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCBS.PRODUCT_CAT_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCBS.TELECOM_PROD_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCBS.CUST_PROD_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCBS.BILL_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCBS.BILL_ITEM_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCBS.USAGE_REC_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCBS.NUMBER_RES_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCOA.API_APP_SEQ TO TELECOM_DEV;
GRANT SELECT ON TCOA.API_CALL_SEQ TO TELECOM_DEV;

-- 3. TELECOM_OPS 用户
CREATE USER TELECOM_OPS IDENTIFIED BY "TelecomOps_123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

-- 运维人员通常只有SELECT权限，用于监控和报告
GRANT CONNECT TO TELECOM_OPS;
GRANT CREATE SESSION TO TELECOM_OPS;
GRANT SELECT ON TCBS.CUSTOMERS TO TELECOM_OPS;
GRANT SELECT ON TCBS.CUSTOMER_ACCOUNTS TO TELECOM_OPS;
GRANT SELECT ON TCBS.PRODUCT_CATEGORIES TO TELECOM_OPS;
GRANT SELECT ON TCBS.TELECOM_PRODUCTS TO TELECOM_OPS;
GRANT SELECT ON TCBS.NUMBER_RESOURCES TO TELECOM_OPS;
GRANT SELECT ON TCBS.SERVICE_CONTRACTS TO TELECOM_OPS;
GRANT SELECT ON TCBS.CUSTOMER_PRODUCTS TO TELECOM_OPS;
GRANT SELECT ON TCBS.CUSTOMER_BILLS TO TELECOM_OPS;
GRANT SELECT ON TCBS.BILL_ITEMS TO TELECOM_OPS;
GRANT SELECT ON TCBS.USAGE_RECORDS TO TELECOM_OPS;
GRANT SELECT ON TCOA.OPEN_API_APPS TO TELECOM_OPS;
GRANT SELECT ON TCOA.API_CALL_LOGS TO TELECOM_OPS;
-- 授予对历史表的SELECT权限
GRANT SELECT ON TCBS.USAGE_RECORDS_YR_2023 TO TELECOM_OPS;
GRANT SELECT ON TCBS.USAGE_RECORDS_MON_202310 TO TELECOM_OPS;
GRANT SELECT ON TCBS.USAGE_RECORDS_MON_202311 TO TELECOM_OPS;
GRANT SELECT ON TCBS.USAGE_RECORDS_MON_202312 TO TELECOM_OPS;
GRANT SELECT ON TCBS.USAGE_RECORDS_DAILY_20231026 TO TELECOM_OPS;
GRANT SELECT ON TCOA.API_CALL_LOGS_MON_202310 TO TELECOM_OPS;
GRANT SELECT ON TCOA.API_CALL_LOGS_MON_202311 TO TELECOM_OPS;
GRANT SELECT ON TCOA.API_CALL_LOGS_MON_202312 TO TELECOM_OPS;
-- 授予常用性能视图的SELECT权限
-- GRANT SELECT ON V_$SESSION TO TELECOM_OPS;
-- GRANT SELECT ON V_$PROCESS TO TELECOM_OPS;
-- GRANT SELECT ON V_$SQL TO TELECOM_OPS;
-- GRANT SELECT ON V_$LOCKED_OBJECT TO TELECOM_OPS;

-- ======================================================================
-- 9. 插入测试数据 (Test Data)
--    注重数据之间的关联性和业务逻辑
--    所有INSERT语句都需要显式指定Schema名称
-- ======================================================================

-- TCBS Schema的数据

-- NUMBER_RESOURCES (模拟20个手机号码)
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13800000001, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13800000002, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13800000003, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13910000001, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13910000002, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13910000003, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13320000001, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13320000002, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13320000003, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (18630000001, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (18630000002, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (18630000003, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (15040000001, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (15040000002, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (15040000003, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (17750000001, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (17750000002, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (17750000003, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13060000001, 'MOBILE_NUMBER', 'AVAILABLE');
INSERT INTO TCBS.NUMBER_RESOURCES (resource_id, resource_type, status) VALUES (13060000002, 'MOBILE_NUMBER', 'AVAILABLE');

-- CUSTOMERS (5 rows)
INSERT INTO TCBS.CUSTOMERS (id_number, customer_name, contact_phone, contact_email, address_line1, city, province, postal_code, status, registration_date)
VALUES ('110101199001011234', '张三', '13800000001', 'zhangsan@example.com', '北京市朝阳区A路1号', '北京', '北京', '100020', 'ACTIVE', TO_TIMESTAMP('2022-01-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TCBS.CUSTOMERS (id_number, customer_name, contact_phone, contact_email, address_line1, city, province, postal_code, status, registration_date)
VALUES ('310101198505055678', '李四', '13910000001', 'lisi@example.com', '上海市浦东新区B路2号', '上海', '上海', '200120', 'ACTIVE', TO_TIMESTAMP('2022-02-15 10:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TCBS.CUSTOMERS (id_number, customer_name, contact_phone, contact_email, address_line1, city, province, postal_code, status, registration_date)
VALUES ('440101199203038901', '王五', '13320000001', 'wangwu@example.com', '广东省广州市C路3号', '广州', '广东', '510000', 'ACTIVE', TO_TIMESTAMP('2022-03-20 11:45:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TCBS.CUSTOMERS (id_number, customer_name, contact_phone, contact_email, address_line1, city, province, postal_code, status, registration_date)
VALUES ('510101197808082345', '赵六', '18630000001', 'zhaoliu@example.com', '四川省成都市D路4号', '成都', '四川', '610000', 'ACTIVE', TO_TIMESTAMP('2022-04-10 14:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TCBS.CUSTOMERS (id_number, customer_name, contact_phone, contact_email, address_line1, city, province, postal_code, status, registration_date)
VALUES ('610101199511116789', '钱七', '15040000001', 'qianqi@example.com', '陕西省西安市E路5号', '西安', '陕西', '710000', 'ACTIVE', TO_TIMESTAMP('2022-05-01 16:20:00', 'YYYY-MM-DD HH24:MI:SS'));

-- CUSTOMER_ACCOUNTS (为每个客户创建主账户)
INSERT INTO TCBS.CUSTOMER_ACCOUNTS (customer_id, account_name, account_type, balance, credit_limit, status, open_date)
SELECT customer_id, customer_name || '主账户', 'INDIVIDUAL', 150.00, 500.00, 'ACTIVE', TO_TIMESTAMP('2022-01-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.CUSTOMERS WHERE customer_name = '张三';
INSERT INTO TCBS.CUSTOMER_ACCOUNTS (customer_id, account_name, account_type, balance, credit_limit, status, open_date)
SELECT customer_id, customer_name || '主账户', 'INDIVIDUAL', 200.00, 500.00, 'ACTIVE', TO_TIMESTAMP('2022-02-15 10:30:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.CUSTOMERS WHERE customer_name = '李四';
INSERT INTO TCBS.CUSTOMER_ACCOUNTS (customer_id, account_name, account_type, balance, credit_limit, status, open_date)
SELECT customer_id, customer_name || '主账户', 'INDIVIDUAL', 50.00, 500.00, 'ACTIVE', TO_TIMESTAMP('2022-03-20 11:45:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.CUSTOMERS WHERE customer_name = '王五';
INSERT INTO TCBS.CUSTOMER_ACCOUNTS (customer_id, account_name, account_type, balance, credit_limit, status, open_date)
SELECT customer_id, customer_name || '主账户', 'INDIVIDUAL', 300.00, 500.00, 'ACTIVE', TO_TIMESTAMP('2022-04-10 14:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.CUSTOMERS WHERE customer_name = '赵六';
INSERT INTO TCBS.CUSTOMER_ACCOUNTS (customer_id, account_name, account_type, balance, credit_limit, status, open_date)
SELECT customer_id, customer_name || '主账户', 'INDIVIDUAL', 100.00, 500.00, 'ACTIVE', TO_TIMESTAMP('2022-05-01 16:20:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.CUSTOMERS WHERE customer_name = '钱七';

-- PRODUCT_CATEGORIES (5 rows)
INSERT INTO TCBS.PRODUCT_CATEGORIES (category_name, description) VALUES ('语音套餐', '包含语音通话分钟数');
INSERT INTO TCBS.PRODUCT_CATEGORIES (category_name, description) VALUES ('流量套餐', '包含手机上网流量');
INSERT INTO TCBS.PRODUCT_CATEGORIES (category_name, description) VALUES ('融合套餐', '包含语音、流量、宽带等');
INSERT INTO TCBS.PRODUCT_CATEGORIES (category_name, description) VALUES ('增值服务', '短信包、彩铃、来电显示等');
INSERT INTO TCBS.PRODUCT_CATEGORIES (category_name, description) VALUES ('终端设备', '手机、路由器等');

-- TELECOM_PRODUCTS (8 rows)
INSERT INTO TCBS.TELECOM_PRODUCTS (product_name, category_id, product_type, base_price, description, validity_period_days, is_active, created_date)
SELECT '5G智享套餐129', category_id, 'PACKAGE', 129.00, '包含30GB通用流量，500分钟国内通话，赠送宽带。', 30, 'Y', TO_TIMESTAMP('2022-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.PRODUCT_CATEGORIES WHERE category_name = '融合套餐';
INSERT INTO TCBS.TELECOM_PRODUCTS (product_name, category_id, product_type, base_price, description, validity_period_days, is_active, created_date)
SELECT '语音畅聊包58', category_id, 'VOICE_PLAN', 58.00, '包含300分钟国内通话。', 30, 'Y', TO_TIMESTAMP('2022-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.PRODUCT_CATEGORIES WHERE category_name = '语音套餐';
INSERT INTO TCBS.TELECOM_PRODUCTS (product_name, category_id, product_type, base_price, description, validity_period_days, is_active, created_date)
SELECT '流量安心包10G', category_id, 'DATA_PLAN', 30.00, '10GB国内通用流量，当月有效。', 30, 'Y', TO_TIMESTAMP('2022-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.PRODUCT_CATEGORIES WHERE category_name = '流量套餐';
INSERT INTO TCBS.TELECOM_PRODUCTS (product_name, category_id, product_type, base_price, description, validity_period_days, is_active, created_date)
SELECT '来电显示', category_id, 'VAS', 6.00, '开通来电显示功能。', 30, 'Y', TO_TIMESTAMP('2022-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.PRODUCT_CATEGORIES WHERE category_name = '增值服务';
INSERT INTO TCBS.TELECOM_PRODUCTS (product_name, category_id, product_type, base_price, description, validity_period_days, is_active, created_date)
SELECT '短信包300条', category_id, 'VAS', 10.00, '每月300条国内短信。', 30, 'Y', TO_TIMESTAMP('2022-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.PRODUCT_CATEGORIES WHERE category_name = '增值服务';
INSERT INTO TCBS.TELECOM_PRODUCTS (product_name, category_id, product_type, base_price, description, validity_period_days, is_active, created_date)
SELECT '千兆宽带套餐', category_id, 'PACKAGE', 99.00, '独立千兆宽带服务，不含手机套餐。', 30, 'Y', TO_TIMESTAMP('2022-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.PRODUCT_CATEGORIES WHERE category_name = '融合套餐';
INSERT INTO TCBS.TELECOM_PRODUCTS (product_name, category_id, product_type, base_price, description, validity_period_days, is_active, created_date)
SELECT 'iPhone 15 Pro Max', category_id, 'DEVICE', 9999.00, '最新款旗舰手机。', NULL, 'Y', TO_TIMESTAMP('2022-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.PRODUCT_CATEGORIES WHERE category_name = '终端设备';
INSERT INTO TCBS.TELECOM_PRODUCTS (product_name, category_id, product_type, base_price, description, validity_period_days, is_active, created_date)
SELECT '家庭共享流量包', category_id, 'DATA_PLAN', 50.00, '20GB家庭共享流量，可与家庭成员共享。', 30, 'Y', TO_TIMESTAMP('2022-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.PRODUCT_CATEGORIES WHERE category_name = '流量套餐';

-- SERVICE_CONTRACTS & CUSTOMER_PRODUCTS (模拟客户签约套餐和增值服务)
-- 客户张三：5G智享套餐129 + 来电显示 (手机号码13800000001)
INSERT INTO TCBS.SERVICE_CONTRACTS (customer_id, account_id, resource_id, start_date, end_date, contract_status, monthly_fee)
SELECT c.customer_id, ca.account_id, 13800000001, TO_TIMESTAMP('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE', 129.00
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '张三' AND ca.account_name = '张三主账户';
UPDATE TCBS.NUMBER_RESOURCES SET status = 'ASSIGNED', assigned_to_customer_id = (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '张三'), assigned_date = TO_TIMESTAMP('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') WHERE resource_id = 13800000001;

INSERT INTO TCBS.CUSTOMER_PRODUCTS (customer_id, account_id, product_id, contract_id, subscribe_date, expire_date, status)
SELECT c.customer_id, ca.account_id, tp.product_id, sc.contract_id, TO_TIMESTAMP('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE'
FROM TCBS.CUSTOMERS c
JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
JOIN TCBS.TELECOM_PRODUCTS tp ON tp.product_name = '5G智享套餐129'
JOIN TCBS.SERVICE_CONTRACTS sc ON sc.customer_id = c.customer_id AND sc.resource_id = 13800000001
WHERE c.customer_name = '张三' AND ca.account_name = '张三主账户';
INSERT INTO TCBS.CUSTOMER_PRODUCTS (customer_id, account_id, product_id, contract_id, subscribe_date, expire_date, status)
SELECT c.customer_id, ca.account_id, tp.product_id, sc.contract_id, TO_TIMESTAMP('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE'
FROM TCBS.CUSTOMERS c
JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
JOIN TCBS.TELECOM_PRODUCTS tp ON tp.product_name = '来电显示'
JOIN TCBS.SERVICE_CONTRACTS sc ON sc.customer_id = c.customer_id AND sc.resource_id = 13800000001
WHERE c.customer_name = '张三' AND ca.account_name = '张三主账户';

-- 客户李四：语音畅聊包58 + 短信包300条 (手机号码13910000001)
INSERT INTO TCBS.SERVICE_CONTRACTS (customer_id, account_id, resource_id, start_date, end_date, contract_status, monthly_fee)
SELECT c.customer_id, ca.account_id, 13910000001, TO_TIMESTAMP('2023-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE', 58.00
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '李四' AND ca.account_name = '李四主账户';
UPDATE TCBS.NUMBER_RESOURCES SET status = 'ASSIGNED', assigned_to_customer_id = (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '李四'), assigned_date = TO_TIMESTAMP('2023-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') WHERE resource_id = 13910000001;

INSERT INTO TCBS.CUSTOMER_PRODUCTS (customer_id, account_id, product_id, contract_id, subscribe_date, expire_date, status)
SELECT c.customer_id, ca.account_id, tp.product_id, sc.contract_id, TO_TIMESTAMP('2023-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE'
FROM TCBS.CUSTOMERS c
JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
JOIN TCBS.TELECOM_PRODUCTS tp ON tp.product_name = '语音畅聊包58'
JOIN TCBS.SERVICE_CONTRACTS sc ON sc.customer_id = c.customer_id AND sc.resource_id = 13910000001
WHERE c.customer_name = '李四' AND ca.account_name = '李四主账户';
INSERT INTO TCBS.CUSTOMER_PRODUCTS (customer_id, account_id, product_id, contract_id, subscribe_date, expire_date, status)
SELECT c.customer_id, ca.account_id, tp.product_id, sc.contract_id, TO_TIMESTAMP('2023-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE'
FROM TCBS.CUSTOMERS c
JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
JOIN TCBS.TELECOM_PRODUCTS tp ON tp.product_name = '短信包300条'
JOIN TCBS.SERVICE_CONTRACTS sc ON sc.customer_id = c.customer_id AND sc.resource_id = 13910000001
WHERE c.customer_name = '李四' AND ca.account_name = '李四主账户';

-- 客户王五：流量安心包10G (手机号码13320000001)
INSERT INTO TCBS.SERVICE_CONTRACTS (customer_id, account_id, resource_id, start_date, end_date, contract_status, monthly_fee)
SELECT c.customer_id, ca.account_id, 13320000001, TO_TIMESTAMP('2023-03-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-03-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE', 30.00
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '王五' AND ca.account_name = '王五主账户';
UPDATE TCBS.NUMBER_RESOURCES SET status = 'ASSIGNED', assigned_to_customer_id = (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '王五'), assigned_date = TO_TIMESTAMP('2023-03-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') WHERE resource_id = 13320000001;

INSERT INTO TCBS.CUSTOMER_PRODUCTS (customer_id, account_id, product_id, contract_id, subscribe_date, expire_date, status)
SELECT c.customer_id, ca.account_id, tp.product_id, sc.contract_id, TO_TIMESTAMP('2023-03-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-03-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE'
FROM TCBS.CUSTOMERS c
JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
JOIN TCBS.TELECOM_PRODUCTS tp ON tp.product_name = '流量安心包10G'
JOIN TCBS.SERVICE_CONTRACTS sc ON sc.customer_id = c.customer_id AND sc.resource_id = 13320000001
WHERE c.customer_name = '王五' AND ca.account_name = '王五主账户';

-- 客户赵六：千兆宽带套餐 (没有绑定手机号码)
INSERT INTO TCBS.SERVICE_CONTRACTS (customer_id, account_id, resource_id, start_date, end_date, contract_status, monthly_fee)
SELECT c.customer_id, ca.account_id, NULL, TO_TIMESTAMP('2023-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE', 99.00
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '赵六' AND ca.account_name = '赵六主账户';

INSERT INTO TCBS.CUSTOMER_PRODUCTS (customer_id, account_id, product_id, contract_id, subscribe_date, expire_date, status)
SELECT c.customer_id, ca.account_id, tp.product_id, sc.contract_id, TO_TIMESTAMP('2023-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE'
FROM TCBS.CUSTOMERS c
JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
JOIN TCBS.TELECOM_PRODUCTS tp ON tp.product_name = '千兆宽带套餐'
JOIN TCBS.SERVICE_CONTRACTS sc ON sc.customer_id = c.customer_id AND sc.resource_id IS NULL
WHERE c.customer_name = '赵六' AND ca.account_name = '赵六主账户';

-- 客户钱七：iPhone 15 Pro Max (设备)
INSERT INTO TCBS.CUSTOMER_PRODUCTS (customer_id, account_id, product_id, contract_id, subscribe_date, expire_date, status)
SELECT c.customer_id, ca.account_id, tp.product_id, NULL, TO_TIMESTAMP('2023-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'ACTIVE'
FROM TCBS.CUSTOMERS c
JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
JOIN TCBS.TELECOM_PRODUCTS tp ON tp.product_name = 'iPhone 15 Pro Max'
WHERE c.customer_name = '钱七' AND ca.account_name = '钱七主账户';


-- CUSTOMER_BILLS & BILL_ITEMS (模拟10月份的账单)
-- 张三 10月账单 (5G智享129 + 来电显示6元)
INSERT INTO TCBS.CUSTOMER_BILLS (customer_id, account_id, bill_period_start, bill_period_end, total_amount, paid_amount, due_date, payment_status, generated_date)
SELECT c.customer_id, ca.account_id, TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 135.00, 135.00, TO_DATE('2023-11-15', 'YYYY-MM-DD'), 'PAID', TO_TIMESTAMP('2023-11-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '张三' AND ca.account_name = '张三主账户';
INSERT INTO TCBS.BILL_ITEMS (bill_id, item_description, item_type, amount)
SELECT bill_id, '5G智享套餐129月费', 'MONTHLY_FEE', 129.00
FROM TCBS.CUSTOMER_BILLS WHERE customer_id = (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '张三') AND bill_period_start=TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');
INSERT INTO TCBS.BILL_ITEMS (bill_id, item_description, item_type, amount)
SELECT bill_id, '来电显示月功能费', 'VAS_FEE', 6.00
FROM TCBS.CUSTOMER_BILLS WHERE customer_id = (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '张三') AND bill_period_start=TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');

-- 李四 10月账单 (语音畅聊58 + 短信包10)
INSERT INTO TCBS.CUSTOMER_BILLS (customer_id, account_id, bill_period_start, bill_period_end, total_amount, paid_amount, due_date, payment_status, generated_date)
SELECT c.customer_id, ca.account_id, TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 68.00, 0.00, TO_DATE('2023-11-15', 'YYYY-MM-DD'), 'OVERDUE', TO_TIMESTAMP('2023-11-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '李四' AND ca.account_name = '李四主账户';
INSERT INTO TCBS.BILL_ITEMS (bill_id, item_description, item_type, amount)
SELECT bill_id, '语音畅聊包58月费', 'MONTHLY_FEE', 58.00
FROM TCBS.CUSTOMER_BILLS WHERE customer_id = (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '李四') AND bill_period_start=TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');
INSERT INTO TCBS.BILL_ITEMS (bill_id, item_description, item_type, amount)
SELECT bill_id, '短信包300条月功能费', 'VAS_FEE', 10.00
FROM TCBS.CUSTOMER_BILLS WHERE customer_id = (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '李四') AND bill_period_start=TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');

-- 王五 10月账单 (流量安心包30)
INSERT INTO TCBS.CUSTOMER_BILLS (customer_id, account_id, bill_period_start, bill_period_end, total_amount, paid_amount, due_date, payment_status, generated_date)
SELECT c.customer_id, ca.account_id, TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 30.00, 30.00, TO_DATE('2023-11-15', 'YYYY-MM-DD'), 'PAID', TO_TIMESTAMP('2023-11-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '王五' AND ca.account_name = '王五主账户';
INSERT INTO TCBS.BILL_ITEMS (bill_id, item_description, item_type, amount)
SELECT bill_id, '流量安心包10G月费', 'MONTHLY_FEE', 30.00
FROM TCBS.CUSTOMER_BILLS WHERE customer_id = (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '王五') AND bill_period_start=TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');

-- 赵六 10月账单 (千兆宽带99)
INSERT INTO TCBS.CUSTOMER_BILLS (customer_id, account_id, bill_period_start, bill_period_end, total_amount, paid_amount, due_date, payment_status, generated_date)
SELECT c.customer_id, ca.account_id, TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 99.00, 0.00, TO_DATE('2023-11-15', 'YYYY-MM-DD'), 'UNPAID', TO_TIMESTAMP('2023-11-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '赵六' AND ca.account_name = '赵六主账户';
INSERT INTO TCBS.BILL_ITEMS (bill_id, item_description, item_type, amount)
SELECT bill_id, '千兆宽带套餐月费', 'MONTHLY_FEE', 99.00
FROM TCBS.CUSTOMER_BILLS WHERE customer_id = (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '赵六') AND bill_period_start=TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');


-- USAGE_RECORDS (模拟一些通话和流量使用记录 - 插入到主表，假设后续会归档)
-- 张三的语音和流量使用
INSERT INTO TCBS.USAGE_RECORDS (customer_id, account_id, resource_id, usage_type, usage_start_time, usage_end_time, duration_seconds, called_number, cost)
SELECT c.customer_id, ca.account_id, 13800000001, 'VOICE', TO_TIMESTAMP('2023-10-05 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-05 10:01:30', 'YYYY-MM-DD HH24:MI:SS'), 90, '13988888888', 0.00
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '张三' AND ca.account_name = '张三主账户';
INSERT INTO TCBS.USAGE_RECORDS (customer_id, account_id, resource_id, usage_type, usage_start_time, data_volume_mb, data_service_type, cost)
SELECT c.customer_id, ca.account_id, 13800000001, 'DATA', TO_TIMESTAMP('2023-10-05 10:05:00', 'YYYY-MM-DD HH24:MI:SS'), 500.25, '5G', 0.00
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '张三' AND ca.account_name = '张三主账户';
INSERT INTO TCBS.USAGE_RECORDS (customer_id, account_id, resource_id, usage_type, usage_start_time, usage_end_time, duration_seconds, called_number, cost)
SELECT c.customer_id, ca.account_id, 13800000001, 'VOICE', TO_TIMESTAMP('2023-10-10 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-10 15:05:00', 'YYYY-MM-DD HH24:MI:SS'), 300, '13677777777', 0.50
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '张三' AND ca.account_name = '张三主账户';

-- 李四的语音和短信使用
INSERT INTO TCBS.USAGE_RECORDS (customer_id, account_id, resource_id, usage_type, usage_start_time, usage_end_time, duration_seconds, called_number, cost)
SELECT c.customer_id, ca.account_id, 13910000001, 'VOICE', TO_TIMESTAMP('2023-10-06 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-06 11:02:00', 'YYYY-MM-DD HH24:MI:SS'), 120, '13766666666', 0.00
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '李四' AND ca.account_name = '李四主账户';
INSERT INTO TCBS.USAGE_RECORDS (customer_id, account_id, resource_id, usage_type, usage_start_time, sms_count, cost)
SELECT c.customer_id, ca.account_id, 13910000001, 'SMS', TO_TIMESTAMP('2023-10-06 11:03:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 0.00
FROM TCBS.CUSTOMERS c JOIN TCBS.CUSTOMER_ACCOUNTS ca ON c.customer_id = ca.customer_id
WHERE c.customer_name = '李四' AND ca.account_name = '李四主账户';


-- TCOA Schema的数据

-- OPEN_API_APPS (2个第三方应用)
INSERT INTO TCOA.OPEN_API_APPS (app_name, developer_name, app_key, app_secret, status, registered_date)
VALUES ('出行服务APP', '智慧交通科技', 'APPKEY_TRAFFIC_12345', 'APPSECRET_TRAFFIC_XYZABC', 'ACTIVE', TO_TIMESTAMP('2023-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TCOA.OPEN_API_APPS (app_name, developer_name, app_key, app_secret, status, registered_date)
VALUES ('金融理财APP', '财富金服', 'APPKEY_FINANCE_67890', 'APPSECRET_FINANCE_UVWXY', 'ACTIVE', TO_TIMESTAMP('2023-03-01 15:00:00', 'YYYY-MM-DD HH24:MI:SS'));

-- API_CALL_LOGS (模拟API调用日志 - 插入到主表，假设后续会归档)
-- 出行服务APP查询张三的套餐详情
INSERT INTO TCOA.API_CALL_LOGS (app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, client_ip, customer_id, request_body, response_body)
SELECT (SELECT app_id FROM TCOA.OPEN_API_APPS WHERE app_name = '出行服务APP'),
    '/v1/customer/package_details',
    TO_TIMESTAMP('2023-10-26 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    'GET',
    200,
    50,
    '192.168.1.100',
    (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '张三'),
    '{"customer_id": "100001"}',
    '{"package_name": "5G智享套餐129", "data_left": "25GB", "voice_left": "400min"}'
FROM DUAL;
-- 金融理财APP查询李四的账单总额
INSERT INTO TCOA.API_CALL_LOGS (app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, client_ip, customer_id, request_body, response_body)
SELECT (SELECT app_id FROM TCOA.OPEN_API_APPS WHERE app_name = '金融理财APP'),
    '/v1/customer/bill_summary',
    TO_TIMESTAMP('2023-10-26 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    'POST',
    200,
    120,
    '203.0.113.50',
    (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '李四'),
    '{"customer_id": "100002", "bill_month": "2023-10"}',
    '{"total_amount": "68.00", "status": "OVERDUE"}'
FROM DUAL;
-- 出行服务APP调用失败
INSERT INTO TCOA.API_CALL_LOGS (app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, client_ip, customer_id, request_body, response_body)
SELECT (SELECT app_id FROM TCOA.OPEN_API_APPS WHERE app_name = '出行服务APP'),
    '/v1/customer/location_track',
    TO_TIMESTAMP('2023-10-26 11:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    'GET',
    403,
    30,
    '192.168.1.100',
    (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '张三'),
    '{"customer_id": "100001"}',
    '{"error": "Permission Denied"}'
FROM DUAL;


-- ######################################################################
-- # 插入测试数据到历史表 (手动模拟数据归档)                            #
-- ######################################################################

-- 模拟将USAGE_RECORDS数据归档到2023年年表和10月月表
INSERT INTO TCBS.USAGE_RECORDS_YR_2023
SELECT usage_id, customer_id, account_id, resource_id, usage_type, usage_start_time, usage_end_time, duration_seconds, data_volume_mb, sms_count, cost, called_number, data_service_type
FROM TCBS.USAGE_RECORDS WHERE usage_start_time >= TO_TIMESTAMP('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND usage_start_time < TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');

INSERT INTO TCBS.USAGE_RECORDS_MON_202310
SELECT usage_id, customer_id, account_id, resource_id, usage_type, usage_start_time, usage_end_time, duration_seconds, data_volume_mb, sms_count, cost, called_number, data_service_type
FROM TCBS.USAGE_RECORDS WHERE usage_start_time >= TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND usage_start_time < TO_TIMESTAMP('2023-11-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');

INSERT INTO TCBS.USAGE_RECORDS_DAILY_20231026
SELECT usage_id, customer_id, account_id, resource_id, usage_type, usage_start_time, usage_end_time, duration_seconds, data_volume_mb, sms_count, cost, called_number, data_service_type
FROM TCBS.USAGE_RECORDS WHERE TRUNC(usage_start_time) = TO_DATE('2023-10-26', 'YYYY-MM-DD');

-- 模拟将API_CALL_LOGS数据归档到2023年10月月表
INSERT INTO TCOA.API_CALL_LOGS_MON_202310
SELECT log_id, app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, request_body, response_body, client_ip, customer_id
FROM TCOA.API_CALL_LOGS WHERE call_timestamp >= TO_TIMESTAMP('2023-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND call_timestamp < TO_TIMESTAMP('2023-11-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');


-- ======================================================================
-- 10. 提交所有更改
-- ======================================================================
COMMIT;

-- 我们以 TCOA 用户的身份来创建
-- 注意：这是一个全新的表，用于学习分区
CREATE TABLE TCOA.API_CALL_LOGS_PART (
    log_id          NUMBER(15)      NOT NULL,
    app_id          NUMBER(10)      CONSTRAINT tcoa_acl_part_app_id_nn NOT NULL,
    api_endpoint    VARCHAR2(200)   CONSTRAINT tcoa_acl_part_endpoint_nn NOT NULL,
    call_timestamp  TIMESTAMP       CONSTRAINT tcoa_acl_part_ts_nn NOT NULL,
    request_method  VARCHAR2(10),
    response_status NUMBER(3)       CONSTRAINT tcoa_acl_part_resp_nn NOT NULL,
    response_time_ms NUMBER(10),
    request_body    CLOB,
    response_body   CLOB,
    client_ip       VARCHAR2(40),
    customer_id     NUMBER(10)
    -- 注意：主键和外键我们先不加，下一课再讲，因为分区表的主键索引有讲究
)
TABLESPACE TS_TCOA_DATA -- 默认表空间
LOB (request_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
LOB (response_body) STORE AS SECUREFILE (TABLESPACE TS_TCBS_LOB)
--
-- ===== 这 里 是 核 心 =====
--
PARTITION BY RANGE (call_timestamp) (
    PARTITION p_202310 VALUES LESS THAN (TO_TIMESTAMP('2023-11-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')) TABLESPACE TBS_TCOA_MON_03_DAT_202310,
    PARTITION p_202311 VALUES LESS THAN (TO_TIMESTAMP('2023-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')) TABLESPACE TBS_TCOA_MON_03_DAT_202311,
    PARTITION p_202312 VALUES LESS THAN (TO_TIMESTAMP('2024-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')) TABLESPACE TBS_TCOA_MON_03_DAT_202312,

    -- OCP 考点：一定要有一个 "最大" 分区，否则新数据会插不进去！
    PARTITION p_max VALUES LESS THAN (MAXVALUE) TABLESPACE TS_TCOA_DATA
);



-- ======================================================================
-- 1. 为 TCOA.API_CALL_LOGS_PART 插入2023年10月的数据 (p_202310 分区)
-- ======================================================================

INSERT INTO TCOA.API_CALL_LOGS_PART (log_id, app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, client_ip, customer_id, request_body, response_body)
SELECT TCOA.API_CALL_SEQ.NEXTVAL,
       (SELECT app_id FROM TCOA.OPEN_API_APPS WHERE app_name = '出行服务APP'),
       '/v1/customer/location',
       TO_TIMESTAMP('2023-10-15 08:30:00', 'YYYY-MM-DD HH24:MI:SS'),
       'GET', 200, 45, '192.168.1.100',
       (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '张三'),
       '{"action": "get_location"}',
       '{"lat": "39.90", "lon": "116.40"}'
FROM DUAL;

INSERT INTO TCOA.API_CALL_LOGS_PART (log_id, app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, client_ip, customer_id, request_body, response_body)
SELECT TCOA.API_CALL_SEQ.NEXTVAL,
       (SELECT app_id FROM TCOA.OPEN_API_APPS WHERE app_name = '金融理财APP'),
       '/v1/customer/credit_check',
       TO_TIMESTAMP('2023-10-20 14:22:00', 'YYYY-MM-DD HH24:MI:SS'),
       'POST', 200, 150, '203.0.113.50',
       (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '李四'),
       '{"id_number": "310101...5678"}',
       '{"credit_score": "750"}'
FROM DUAL;


-- ======================================================================
-- 2. 为 TCOA.API_CALL_LOGS_PART 插入2023年11月的数据 (p_202311 分区)
-- ======================================================================

INSERT INTO TCOA.API_CALL_LOGS_PART (log_id, app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, client_ip, customer_id, request_body, response_body)
SELECT TCOA.API_CALL_SEQ.NEXTVAL,
       (SELECT app_id FROM TCOA.OPEN_API_APPS WHERE app_name = '出行服务APP'),
       '/v1/customer/package_details',
       TO_TIMESTAMP('2023-11-10 10:10:10', 'YYYY-MM-DD HH24:MI:SS'),
       'GET', 200, 55, '192.168.1.102',
       (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '王五'),
       '{"customer_id": "100003"}',
       '{"package_name": "流量安心包10G", "data_left": "8GB"}'
FROM DUAL;

INSERT INTO TCOA.API_CALL_LOGS_PART (log_id, app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, client_ip, customer_id, request_body, response_body)
SELECT TCOA.API_CALL_SEQ.NEXTVAL,
       (SELECT app_id FROM TCOA.OPEN_API_APPS WHERE app_name = '金融理财APP'),
       '/v1/customer/bill_summary',
       TO_TIMESTAMP('2023-11-25 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       'POST', 404, 30, '203.0.113.51',
       (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '赵六'),
       '{"customer_id": "100004", "bill_month": "2023-10"}',
       '{"error": "bill_not_found"}'
FROM DUAL;


-- ======================================================================
-- 3. 为 TCOA.API_CALL_LOGS_PART 插入2023年12月的数据 (p_202312 分区)
-- ======================================================================

INSERT INTO TCOA.API_CALL_LOGS_PART (log_id, app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, client_ip, customer_id, request_body, response_body)
SELECT TCOA.API_CALL_SEQ.NEXTVAL,
       (SELECT app_id FROM TCOA.OPEN_API_APPS WHERE app_name = '出行服务APP'),
       '/v1/customer/location',
       TO_TIMESTAMP('2023-12-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       'GET', 200, 48, '192.168.1.100',
       (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '钱七'),
       '{"action": "get_location"}',
       '{"lat": "31.23", "lon": "121.47"}'
FROM DUAL;

-- ======================================================================
-- 4. 为 TCOA.API_CALL_LOGS_PART 插入2024年1月的数据 (p_max 分区)
-- ======================================================================

INSERT INTO TCOA.API_CALL_LOGS_PART (log_id, app_id, api_endpoint, call_timestamp, request_method, response_status, response_time_ms, client_ip, customer_id, request_body, response_body)
SELECT TCOA.API_CALL_SEQ.NEXTVAL,
       (SELECT app_id FROM TCOA.OPEN_API_APPS WHERE app_name = '出行服务APP'),
       '/v1/customer/package_details',
       TO_TIMESTAMP('2024-01-05 11:11:11', 'YYYY-MM-DD HH24:MI:SS'),
       'GET', 200, 50, '192.168.1.100',
       (SELECT customer_id FROM TCBS.CUSTOMERS WHERE customer_name = '张三'),
       '{"customer_id": "100001"}',
       '{"package_name": "5G智享套餐129", "data_left": "28GB"}'
FROM DUAL;


COMMIT;